In [1]:
# Importing Libraries

In [2]:
import pandas as pd
import numpy as np
import os

In [4]:
df = pd.read_csv("C:/Users/Bhanu Bisht/Data_Analytics_Project/data/raw/07_scheme_performance.csv")

In [12]:
df

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low
5,100016,HDFC Top 100 Fund - Regular Plan - Growth,HDFC Mutual Fund,Large Cap,Regular,10.94,14.84,11.32,14.06,0.78,0.97,1.06,1.70,14.0,-17.41,6434,1.55,5,Moderate
6,125497,HDFC Top 100 Fund - Direct Plan - Growth,HDFC Mutual Fund,Large Cap,Direct,11.48,13.38,13.48,12.25,1.13,0.97,0.96,1.45,14.0,-33.50,10611,0.92,4,Moderate
7,100033,HDFC Mid-Cap Opportunities Fund - Regular - Gr...,HDFC Mutual Fund,Mid Cap,Regular,15.43,16.58,17.69,15.63,0.95,0.91,0.87,1.44,19.0,-13.67,23185,1.38,5,High
8,125498,HDFC Mid-Cap Opportunities Fund - Direct - Growth,HDFC Mutual Fund,Mid Cap,Direct,19.98,15.29,15.85,14.39,0.90,1.04,0.80,1.38,19.0,-32.22,18792,0.78,4,High
9,100025,HDFC Short Term Debt Fund - Regular - Growth,HDFC Mutual Fund,Short Duration,Regular,6.83,7.37,6.41,5.39,1.98,0.44,1.84,2.79,4.0,-6.01,27953,0.56,3,Low
10,120503,ICICI Pru Bluechip Fund - Regular - Growth,ICICI Prudential MF,Large Cap,Regular,15.63,11.54,11.46,10.88,0.66,0.96,0.82,1.12,14.0,-25.91,36022,1.42,4,Moderate
11,120504,ICICI Pru Bluechip Fund - Direct - Growth,ICICI Prudential MF,Large Cap,Direct,14.12,14.41,13.02,13.53,0.88,1.03,1.03,1.27,14.0,-26.59,41553,0.80,3,Moderate
12,120505,ICICI Pru Midcap Fund - Regular - Growth,ICICI Prudential MF,Mid Cap,Regular,14.02,18.08,17.55,17.19,0.89,1.00,0.95,1.45,19.0,-21.84,979,1.36,3,High
13,120506,ICICI Pru Value Discovery Fund - Regular - Growth,ICICI Prudential MF,Value,Regular,16.67,14.76,12.60,14.21,0.55,0.92,0.98,1.50,15.0,-21.89,2571,1.41,4,Moderately High
14,120507,ICICI Pru Liquid Fund - Regular - Growth,ICICI Prudential MF,Liquid,Regular,8.89,7.68,7.94,5.83,1.85,0.26,7.68,10.37,0.5,-2.62,39116,0.74,5,Low
15,118632,Nippon India Large Cap Fund - Regular - Growth,Nippon India MF,Large Cap,Regular,15.84,14.00,14.70,13.14,0.86,0.88,1.00,1.68,14.0,-16.07,20909,1.51,4,Moderate
16,118633,Nippon India Large Cap Fund - Direct - Growth,Nippon India MF,Large Cap,Direct,14.42,12.33,14.72,10.63,1.70,1.02,0.88,1.48,14.0,-18.14,39475,0.72,3,Moderate
17,118634,Nippon India Small Cap Fund - Regular - Growth,Nippon India MF,Small Cap,Regular,21.30,20.15,21.88,19.35,0.80,1.03,0.81,1.14,25.0,-30.87,43630,1.53,4,Very High
18,118635,Nippon India ETF Nifty 50 BeES,Nippon India MF,Index/ETF,Direct,10.14,11.77,12.31,9.97,1.80,1.04,0.91,1.24,13.0,-26.75,20284,0.89,5,Moderate
19,118636,Nippon India Gilt Securities Fund - Regular - ...,Nippon India MF,Gilt,Regular,6.19,5.31,8.71,4.42,0.89,0.37,1.33,2.38,4.0,-2.23,30030,0.55,4,Low
20,120841,Kotak Bluechip Fund - Regular - Growth,Kotak Mahindra MF,Large Cap,Regular,14.37,12.25,13.42,10.98,1.27,0.93,0.87,1.34,14.0,-17.86,35585,1.59,3,Moderate
21,120842,Kotak Emerging Equity Fund - Regular - Growth,Kotak Mahindra MF,Mid Cap,Regular,17.12,18.23,17.75,16.32,1.91,1.00,0.96,1.27,19.0,-21.92,47469,1.56,4,High
22,120843,Kotak Flexicap Fund - Regular - Growth,Kotak Mahindra MF,Flexi Cap,Regular,15.74,15.65,13.50,13.80,1.85,0.95,0.98,1.57,16.0,-19.50,35012,1.45,5,Moderately High
23,120844,Kotak Liquid Fund - Regular - Growth,Kotak Mahindra MF,Liquid,Regular,4.26,6.18,8.26,4.66,1.52,0.47,6.18,9.70,0.5,-3.81,27623,0.60,3,Low
24,119092,Axis Bluechip Fund - Regular - Growth,Axis Mutual Fund,Large Cap,Regular,11.82,11.84,14.14,10.43,1.41,0.91,0.85,1.25,14.0,-27.54,25803,1.64,4,Moderate
25,119093,Axis Bluechip Fund - Direct - Growth,Axis Mutual Fund,Large Cap,Direct,13.95,12.14,13.66,10.71,1.43,0.87,0.87,1.54,14.0,-17.40,15866,0.75,4,Moderate
26,119094,Axis Midcap Fund - Regular - Growth,Axis Mutual Fund,Mid Cap,Regular,14.88,15.18,18.94,13.76,1.42,1.00,0.80,1.18,19.0,-32.38,28996,1.38,5,High
27,119095,Axis Small Cap Fund - Regular - Growth,Axis Mutual Fund,Small Cap,Regular,21.97,20.98,22.62,20.47,0.51,1.00,0.84,1.40,25.0,-14.45,21545,1.38,4,Very High
28,101206,ABSL Frontline Equity Fund - Regular - Growth,Aditya Birla Sun Life MF,Large Cap,Regular,14.82,13.78,12.86,12.44,1.34,1.03,0.98,1.25,14.0,-15.07,23500,1.60,5,Moderate
29,101207,ABSL Small Cap Fund - Regular - Growth,Aditya Birla Sun Life MF,Small Cap,Regular,24.93,22.38,23.80,20.54,1.84,0.97,0.90,1.47,25.0,-23.61,41613,1.53,5,Very High
30,101208,ABSL Liquid Fund - Regular - Growth,Aditya Birla Sun Life MF,Liquid,Regular,6.18,5.14,7.95,3.96,1.18,0.43,5.14,8.76,0.5,-3.66,38995,0.79,5,Low
31,102885,UTI Nifty 50 Index Fund - Regular - Growth,UTI Mutual Fund,Index,Regular,13.76,12.10,11.31,11.17,0.93,0.90,0.93,1.29,13.0,-24.42,7350,1.57,4,Moderate
32,102886,UTI Mid Cap Fund - Regular - Growth,UTI Mutual Fund,Mid Cap,Regular,16.30,15.61,15.86,14.49,1.12,0.92,0.82,1.21,19.0,-13.43,41728,1.51,5,High
33,102887,UTI Flexi Cap Fund - Regular - Growth,UTI Mutual Fund,Flexi Cap,Regular,17.43,15.34,15.78,13.55,1.79,1.00,0.96,1.37,16.0,-12.14,17912,1.64,5,Moderately High
34,148567,Mirae Asset Large Cap Fund - Regular - Growth,Mirae Asset MF,Large Cap,Regular,15.12,14.81,12.68,13.19,1.62,0.96,1.06,1.66,14.0,-17.07,11361,1.46,5,Moderate
35,148568,Mirae Asset Emerging Bluechip Fund - Regular -...,Mirae Asset MF,Large & Mid Cap,Regular,14.91,14.56,15.68,12.86,1.70,0.99,0.91,1.55,16.0,-33.15,49046,1.52,5,Moderately High
36,148569,Mirae Asset Tax Saver Fund - Regular - Growth,Mirae Asset MF,ELSS,Regular,11.16,13.58,14.26,13.04,0.54,0.98,0.80,1.03,17.0,-22.62,2989,1.60,5,High
37,149322,DSP Top 100 Equity Fund - Regular - Growth,DSP Mutual Fund,Large Cap,Regular,11.96,12.82,12.35,11.00,1.82,0.91,0.92,1.63,14.0,-21.70,41828,1.54,5,Moderate
38,149323,DSP Midcap Fund - Regular - Growth,DSP Mutual Fund,Mid Cap,Regular,14.12,17.16,19.00,16.14,1.02,0.98,0.90,1.50,19.0,-26.99,37835,1.61,4,High
39,149324,DSP Small Cap Fund - Regular - Growth,DSP Mutual Fund,Small Cap,Regular,20.20,20.08,20.61,19.39,0.69,0.98,0.80,1.23,25.0,-17.01,35124,1.52,4,Very High

In [6]:
df.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [7]:
df.tail()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
35,148568,Mirae Asset Emerging Bluechip Fund - Regular -...,Mirae Asset MF,Large & Mid Cap,Regular,14.91,14.56,15.68,12.86,1.70,0.99,0.91,1.55,16.0,-33.15,49046,1.52,5,Moderately High
36,148569,Mirae Asset Tax Saver Fund - Regular - Growth,Mirae Asset MF,ELSS,Regular,11.16,13.58,14.26,13.04,0.54,0.98,0.80,1.03,17.0,-22.62,2989,1.60,5,High
37,149322,DSP Top 100 Equity Fund - Regular - Growth,DSP Mutual Fund,Large Cap,Regular,11.96,12.82,12.35,11.00,1.82,0.91,0.92,1.63,14.0,-21.70,41828,1.54,5,Moderate
38,149323,DSP Midcap Fund - Regular - Growth,DSP Mutual Fund,Mid Cap,Regular,14.12,17.16,19.00,16.14,1.02,0.98,0.90,1.50,19.0,-26.99,37835,1.61,4,High
39,149324,DSP Small Cap Fund - Regular - Growth,DSP Mutual Fund,Small Cap,Regular,20.20,20.08,20.61,19.39,0.69,0.98,0.80,1.23,25.0,-17.01,35124,1.52,4,Very High

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

In [9]:
df.shape

(40, 19)

In [10]:
df.dtypes

amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object

In [13]:
df.columns

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='object')

In [14]:
df.describe

<bound method NDFrame.describe of     amfi_code                                        scheme_name  \
0      119551          SBI Bluechip Fund - Regular Plan - Growth
1      119552           SBI Bluechip Fund - Direct Plan - Growth
2      119598         SBI Small Cap Fund - Regular Plan - Growth
3      119599          SBI Small Cap Fund - Direct Plan - Growth
4      119120       SBI Magnum Gilt Fund - Regular Plan - Growth
5      100016          HDFC Top 100 Fund - Regular Plan - Growth
6      125497           HDFC Top 100 Fund - Direct Plan - Growth
7      100033  HDFC Mid-Cap Opportunities Fund - Regular - Gr...
8      125498  HDFC Mid-Cap Opportunities Fund - Direct - Growth
9      100025       HDFC Short Term Debt Fund - Regular - Growth
10     120503         ICICI Pru Bluechip Fund - Regular - Growth
11     120504          ICICI Pru Bluechip Fund - Direct - Growth
12     120505           ICICI Pru Midcap Fund - Regular - Growth
13     120506  ICICI Pru Value Discovery Fund - Regular - Growth
14     120507           ICICI Pru Liquid Fund - Regular - Growth
15     118632     Nippon India Large Cap Fund - Regular - Growth
16     118633      Nippon India Large Cap Fund - Direct - Growth
17     118634     Nippon India Small Cap Fund - Regular - Growth
18     118635                     Nippon India ETF Nifty 50 BeES
19     118636  Nippon India Gilt Securities Fund - Regular - ...
20     120841             Kotak Bluechip Fund - Regular - Growth
21     120842      Kotak Emerging Equity Fund - Regular - Growth
22     120843             Kotak Flexicap Fund - Regular - Growth
23     120844               Kotak Liquid Fund - Regular - Growth
24     119092              Axis Bluechip Fund - Regular - Growth
25     119093               Axis Bluechip Fund - Direct - Growth
26     119094                Axis Midcap Fund - Regular - Growth
27     119095             Axis Small Cap Fund - Regular - Growth
28     101206      ABSL Frontline Equity Fund - Regular - Growth
29     101207             ABSL Small Cap Fund - Regular - Growth
30     101208                ABSL Liquid Fund - Regular - Growth
31     102885         UTI Nifty 50 Index Fund - Regular - Growth
32     102886                UTI Mid Cap Fund - Regular - Growth
33     102887              UTI Flexi Cap Fund - Regular - Growth
34     148567      Mirae Asset Large Cap Fund - Regular - Growth
35     148568  Mirae Asset Emerging Bluechip Fund - Regular -...
36     148569      Mirae Asset Tax Saver Fund - Regular - Growth
37     149322         DSP Top 100 Equity Fund - Regular - Growth
38     149323                 DSP Midcap Fund - Regular - Growth
39     149324              DSP Small Cap Fund - Regular - Growth

                  fund_house         category     plan  return_1yr_pct  \
0            SBI Mutual Fund        Large Cap  Regular           12.42
1            SBI Mutual Fund        Large Cap   Direct           15.25
2            SBI Mutual Fund        Small Cap  Regular           24.56
3            SBI Mutual Fund        Small Cap   Direct           20.59
4            SBI Mutual Fund             Gilt  Regular            5.34
5           HDFC Mutual Fund        Large Cap  Regular           10.94
6           HDFC Mutual Fund        Large Cap   Direct           11.48
7           HDFC Mutual Fund          Mid Cap  Regular           15.43
8           HDFC Mutual Fund          Mid Cap   Direct           19.98
9           HDFC Mutual Fund   Short Duration  Regular            6.83
10       ICICI Prudential MF        Large Cap  Regular           15.63
11       ICICI Prudential MF        Large Cap   Direct           14.12
12       ICICI Prudential MF          Mid Cap  Regular           14.02
13       ICICI Prudential MF            Value  Regular           16.67
14       ICICI Prudential MF           Liquid  Regular            8.89
15           Nippon India MF        Large Cap  Regular           15.84
16           Nippon India MF        Large Cap   Direct           14.42
17           Nippon India MF        Small Cap  Regular           21.30
18           Nippon India MF        Index/ETF   Direct           10.14
19           Nippon India MF             Gilt  Regular            6.19
20         Kotak Mahindra MF        Large Cap  Regular           14.37
21         Kotak Mahindra MF          Mid Cap  Regular           17.12
22         Kotak Mahindra MF        Flexi Cap  Regular           15.74
23         Kotak Mahindra MF           Liquid  Regular            4.26
24          Axis Mutual Fund        Large Cap  Regular           11.82
25          Axis Mutual Fund        Large Cap   Direct           13.95
26          Axis Mutual Fund          Mid Cap  Regular           14.88
27          Axis Mutual Fund        Small Cap  Regular           21.97
28  Aditya Birla Sun Life MF        Large Cap  Regular           14.82
29  Aditya Birla Sun Life MF        Small Cap  Regular           24.93
30  Aditya Birla Sun Life MF           Liquid  Regular            6.18
31           UTI Mutual Fund            Index  Regular           13.76
32           UTI Mutual Fund          Mid Cap  Regular           16.30
33           UTI Mutual Fund        Flexi Cap  Regular           17.43
34            Mirae Asset MF        Large Cap  Regular           15.12
35            Mirae Asset MF  Large & Mid Cap  Regular           14.91
36            Mirae Asset MF             ELSS  Regular           11.16
37           DSP Mutual Fund        Large Cap  Regular           11.96
38           DSP Mutual Fund          Mid Cap  Regular           14.12
39           DSP Mutual Fund        Small Cap  Regular           20.20

    return_3yr_pct  return_5yr_pct  benchmark_3yr_pct  alpha  beta  \
0            12.36           14.45              11.49   0.87  0.89
1            11.30           14.23               9.52   1.78  0.87
2            23.39           20.67              22.16   1.23  0.89
3            23.14           21.82              22.01   1.13  1.04
4             6.07            5.43               4.47   1.60  0.22
5            14.84           11.32              14.06   0.78  0.97
6            13.38           13.48              12.25   1.13  0.97
7            16.58           17.69              15.63   0.95  0.91
8            15.29           15.85              14.39   0.90  1.04
9             7.37            6.41               5.39   1.98  0.44
10           11.54           11.46              10.88   0.66  0.96
11           14.41           13.02              13.53   0.88  1.03
12           18.08           17.55              17.19   0.89  1.00
13           14.76           12.60              14.21   0.55  0.92
14            7.68            7.94               5.83   1.85  0.26
15           14.00           14.70              13.14   0.86  0.88
16           12.33           14.72              10.63   1.70  1.02
17           20.15           21.88              19.35   0.80  1.03
18           11.77           12.31               9.97   1.80  1.04
19            5.31            8.71               4.42   0.89  0.37
20           12.25           13.42              10.98   1.27  0.93
21           18.23           17.75              16.32   1.91  1.00
22           15.65           13.50              13.80   1.85  0.95
23            6.18            8.26               4.66   1.52  0.47
24           11.84           14.14              10.43   1.41  0.91
25           12.14           13.66              10.71   1.43  0.87
26           15.18           18.94              13.76   1.42  1.00
27           20.98           22.62              20.47   0.51  1.00
28           13.78           12.86              12.44   1.34  1.03
29           22.38           23.80              20.54   1.84  0.97
30            5.14            7.95               3.96   1.18  0.43
31           12.10           11.31              11.17   0.93  0.90
32           15.61           15.86              14.49   1.12  0.92
33           15.34           15.78              13.55   1.79  1.00
34           14.81           12.68              13.19   1.62  0.96
35           14.56           15.68              12.86   1.70  0.99
36           13.58           14.26              13.04   0.54  0.98
37           12.82           12.35              11.00   1.82  0.91
38           17.16           19.00              16.14   1.02  0.98
39           20.08           20.61              19.39   0.69  0.98

    sharpe_ratio  sortino_ratio  std_dev_ann_pct  max_drawdown_pct  aum_crore  \
0           0.88           1.29             14.0            -21.70      14288
1           0.81           1.29             14.0            -24.43       1231
2           0.94           1.35             25.0            -13.35      19259
3           0.93           1.67             25.0            -24.78      36061
4           1.52           2.11              4.0             -2.30      24101
5           1.06           1.70             14.0            -17.41       6434
6           0.96           1.45             14.0            -33.50      10611
7           0.87           1.44             19.0            -13.67      23185
8           0.80           1.38             19.0            -32.22      18792
9           1.84           2.79              4.0             -6.01      27953
10          0.82           1.12             14.0            -25.91      36022
11          1.03           1.27             14.0            -26.59      41553
12          0.95           1.45             19.0            -21.84        979
13          0.98           1.50             15.0            -21.89       2571
14          7.68          10.37              0.5             -2.62      39116
15          1.00           1.68             14.0            -16.07      20909
16          0.88           1.48             14.0            -18.14      39475
17          0.81           1.14             25.0            -30.87      43630
18          0.91           1.24             13.0            -26.75      20284
19          1.33           2.38              4.0             -2.23      30030
20          0.87           1.34             14.0            -17.86      35585
21          0.96           1.27             19.0            -21.92      47469
22          0.98           1.57             16.0            -19.50      35012
23          6.18           9.70              0.5             -3.81      27623
24          0.85           1.25             14.0            -27.54      25803
25          0.87           1.54             14.0            -17.40      15866
26          0.80           1.18             19.0            -32.38      28996
27          0.84           1.40             25.0            -14.45      21545
28          0.98           1.25             14.0            -15.07      23500
29          0.90           1.47             25.0            -23.61      41613
30          5.14           8.76              0.5             -3.66      38995
31          0.93           1.29             13.0            -24.42       7350
32          0.82           1.21             19.0            -13.43      41728
33          0.96           1.37             16.0            -12.14      17912
34          1.06           1.66             14.0            -17.07      11361
35          0.91           1.55             16.0            -33.15      49046
36          0.80           1.03             17.0            -22.62       2989
37          0.92           1.63             14.0            -21.70      41828
38          0.90           1.50             19.0            -26.99      37835
39          0.80           1.23             25.0            -17.01      35124

    expense_ratio_pct  morningstar_rating       risk_grade
0                1.54                   4         Moderate
1                0.66                   3         Moderate
2                1.43                   5        Very High
3                0.72                   4        Very High
4                0.77                   5              Low
5                1.55                   5         Moderate
6                0.92                   4         Moderate
7                1.38                   5             High
8                0.78                   4             High
9                0.56                   3              Low
10               1.42                   4         Moderate
11               0.80                   3         Moderate
12               1.36                   3             High
13               1.41                   4  Moderately High
14               0.74                   5              Low
15               1.51                   4         Moderate
16               0.72                   3         Moderate
17               1.53                   4        Very High
18               0.89                   5         Moderate
19               0.55                   4              Low
20               1.59                   3         Moderate
21               1.56                   4             High
22               1.45                   5  Moderately High
23               0.60                   3              Low
24               1.64                   4         Moderate
25               0.75                   4         Moderate
26               1.38                   5             High
27               1.38                   4        Very High
28               1.60                   5         Moderate
29               1.53                   5        Very High
30               0.79                   5              Low
31               1.57                   4         Moderate
32               1.51                   5             High
33               1.64                   5  Moderately High
34               1.46                   5         Moderate
35               1.52                   5  Moderately High
36               1.60                   5             High
37               1.54                   5         Moderate
38               1.61                   4             High
39               1.52                   4        Very High  >

In [15]:
df.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

In [17]:
#1. Validate return columns are numeric

In [26]:
return_cols = [
    'return_1yr_pct',
    'return_3yr_pct',
    'return_5yr_pct',
    'benchmark_3yr_pct'
]

for col in return_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

print(df[return_cols].dtypes)

return_1yr_pct       float64
return_3yr_pct       float64
return_5yr_pct       float64
benchmark_3yr_pct    float64
dtype: object

In [29]:
invalid_returns = df[df[return_cols].isnull().any(axis=1)]

print("Rows with invalid return values:", len(invalid_returns))

Rows with invalid return values: 0

In [30]:
#2. Flag anomalous return values

In [31]:
# Mutual fund returns beyond ±100% are unusual and should be reviewed.

In [32]:
anomalies = df[
    (df[return_cols] > 100).any(axis=1) |
    (df[return_cols] < -100).any(axis=1)
]

print("Anomalous return rows:", len(anomalies))
display(anomalies)

Anomalous return rows: 0

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [33]:
# 3. Validate expense ratio range (0.1%–2.5%)

In [34]:
expense_anomalies = df[
    (df['expense_ratio_pct'] < 0.1) |
    (df['expense_ratio_pct'] > 2.5)
]

print("Expense ratio anomalies:", len(expense_anomalies))
display(expense_anomalies[
    ['amfi_code', 'scheme_name', 'expense_ratio_pct']
])

Expense ratio anomalies: 0

Empty DataFrame
Columns: [amfi_code, scheme_name, expense_ratio_pct]
Index: []

In [35]:
#4. Additional quality checks

In [36]:
# Morningstar rating

In [37]:
df[
    ~df['morningstar_rating'].between(1, 5)
]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [38]:
#Beta

In [39]:
df[
    (df['beta'] < 0) | (df['beta'] > 3)
]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [41]:
#AUM

In [42]:
df[
    df['aum_crore'] <= 0
]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [43]:
#Duplicate schemes

In [44]:
duplicates = df[df.duplicated(subset=['amfi_code'], keep=False)]
print("Duplicate AMFI codes:", len(duplicates))

Duplicate AMFI codes: 0

# SQLite Star Schema

In [45]:
#Dimension Tables

In [47]:
# I am Using sqlite3

In [48]:
import sqlite3

In [49]:
# Create/connect database
conn = sqlite3.connect('mutual_fund.db')
# Create cursor
cursor = conn.cursor()

In [50]:
# Execute SQL
cursor.execute("""
CREATE TABLE dim_fund (
    fund_key INTEGER PRIMARY KEY AUTOINCREMENT,
    amfi_code INTEGER UNIQUE NOT NULL,
    scheme_name TEXT NOT NULL,
    fund_house TEXT NOT NULL,
    category TEXT,
    plan TEXT,
    risk_grade TEXT
);
""")

In [51]:
# Save changes
conn.commit()

print("Table created successfully!")

# Close connection
conn.close()

Table created successfully!

In [53]:
#Verify the table was created

In [56]:
conn = sqlite3.connect('mutual_fund.db')
cursor = conn.cursor()

cursor.execute("""
SELECT name
FROM sqlite_master
WHERE type='table';
""")

print(cursor.fetchall())

conn.close()

[('dim_fund',), ('sqlite_sequence',)]

In [58]:
#Fetch all rows and columns

In [57]:
conn = sqlite3.connect('mutual_fund.db')

query = "SELECT * FROM dim_fund"

df = pd.read_sql_query(query, conn)

print(df.head())

conn.close()

Empty DataFrame
Columns: [fund_key, amfi_code, scheme_name, fund_house, category, plan, risk_grade]
Index: []

In [59]:
#Fetch only specific columns

In [63]:
conn = sqlite3.connect("mutual_fund.db")  # (mutual_fund) is database file name

query = """
SELECT
    fund_key,
    amfi_code,
    scheme_name,
    fund_house
FROM dim_fund
"""

df = pd.read_sql_query(query, conn)

print(df.head())

Empty DataFrame
Columns: [fund_key, amfi_code, scheme_name, fund_house]
Index: []

In [65]:
# See only the column names (schema)

In [66]:
conn = sqlite3.connect('mutual_fund.db')
cursor = conn.cursor()

cursor.execute("PRAGMA table_info(dim_fund)")

for col in cursor.fetchall():
    print(col)

(0, 'fund_key', 'INTEGER', 0, None, 1)
(1, 'amfi_code', 'INTEGER', 1, None, 0)
(2, 'scheme_name', 'TEXT', 1, None, 0)
(3, 'fund_house', 'TEXT', 1, None, 0)
(4, 'category', 'TEXT', 0, None, 0)
(5, 'plan', 'TEXT', 0, None, 0)
(6, 'risk_grade', 'TEXT', 0, None, 0)

In [67]:
# if we want Get only column names

In [68]:
cursor.execute("PRAGMA table_info(dim_fund)")

columns = [col[1] for col in cursor.fetchall()]

print(columns)

['fund_key', 'amfi_code', 'scheme_name', 'fund_house', 'category', 'plan', 'risk_grade']

In [70]:
conn = sqlite3.connect("mutual_fund.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date DATE NOT NULL,
    day INTEGER,
    month INTEGER,
    quarter INTEGER,
    year INTEGER
);
""")

conn.commit()

print("dim_date table created successfully!")

conn.close()

dim_date table created successfully!

In [71]:
#Fact NAV

In [75]:
conn = sqlite3.connect("mutual_fund.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE fact_nav (
    nav_key INTEGER PRIMARY KEY AUTOINCREMENT,
    fund_key INTEGER NOT NULL,
    date_key INTEGER NOT NULL,
    nav_value REAL NOT NULL,

    FOREIGN KEY (fund_key)
        REFERENCES dim_fund(fund_key),

    FOREIGN KEY (date_key)
        REFERENCES dim_date(date_key)
);
""")

conn.commit()

print(" fact_nav table created successfully!")

conn.close()

 fact_nav table created successfully!

In [77]:
#### I create connection everytime however we can create all the table in 1 times and then close the connection

In [78]:
'''
conn = sqlite3.connect("mutual_fund.db")
cursor = conn.cursor()

cursor.execute("""
# we create table inside this code
""")

conn.commit()

print(" fact_nav table created successfully!")

conn.close()
'''

'\nconn = sqlite3.connect("mutual_fund.db")\ncursor = conn.cursor()\n\ncursor.execute("""\n# we create table inside this code\n""")\n\nconn.commit()\n\nprint(" fact_nav table created successfully!")\n\nconn.close()\n'

In [76]:
#Fact Transactions

In [79]:
conn = sqlite3.connect("mutual_fund.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE fact_transactions (
    transaction_key INTEGER PRIMARY KEY AUTOINCREMENT,
    investor_id INTEGER NOT NULL,
    fund_key INTEGER NOT NULL,
    date_key INTEGER NOT NULL,

    transaction_type TEXT NOT NULL,
    amount REAL NOT NULL,
    units REAL,

    FOREIGN KEY (fund_key)
        REFERENCES dim_fund(fund_key),

    FOREIGN KEY (date_key)
        REFERENCES dim_date(date_key)
);
""")

conn.commit()

print(" fact_nav table created successfully!")

conn.close()

 fact_nav table created successfully!

In [80]:
# Fact Performance

In [81]:
conn = sqlite3.connect("mutual_fund.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE fact_performance (
    performance_key INTEGER PRIMARY KEY AUTOINCREMENT,
    fund_key INTEGER NOT NULL,

    return_1yr_pct REAL,
    return_3yr_pct REAL,
    return_5yr_pct REAL,

    benchmark_3yr_pct REAL,
    alpha REAL,
    beta REAL,
    sharpe_ratio REAL,
    sortino_ratio REAL,
    std_dev_ann_pct REAL,
    max_drawdown_pct REAL,

    morningstar_rating INTEGER,
    expense_ratio_pct REAL,

    FOREIGN KEY (fund_key)
        REFERENCES dim_fund(fund_key)
);
""")

conn.commit()

print(" fact_nav table created successfully!")

conn.close()

 fact_nav table created successfully!

In [82]:
#Fact AUM

In [83]:
conn = sqlite3.connect("mutual_fund.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE fact_aum (
    aum_key INTEGER PRIMARY KEY AUTOINCREMENT,
    fund_key INTEGER NOT NULL,
    date_key INTEGER NOT NULL,

    aum_crore REAL NOT NULL,

    FOREIGN KEY (fund_key)
        REFERENCES dim_fund(fund_key),

    FOREIGN KEY (date_key)
        REFERENCES dim_date(date_key)
);
""")

conn.commit()

print(" fact_nav table created successfully!")

conn.close()

 fact_nav table created successfully!

In [86]:
print(df.columns.tolist())

['fund_key', 'amfi_code', 'scheme_name', 'fund_house']